apiVersion: apps/v1
kind: Deployment
metadata:
  name: me-app
  namespace: hoopla
  labels:
    app: me-app
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: hoopla/me-app.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: me-app
  template:
    metadata:
      labels:
        app: me-app
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:latest
          imagePullPolicy: Always
